#chatgpt:
#  token: ""
#  proxy-host: 127.0.0.1 #需要代理时必填
#  proxy-port: 8080 #需要代理时必填
#  chat-model: gpt-3.5-turbo
#  session-expiration-time: 10

openai:
  #  proxyHost: "127.0.0.1"
  #  proxyPort: 7890
  keys: 

server:
  port: 8081


youdao:
  appKey: 
  appSecret: 
  from: auto
  to: zh-CHS



