#chatgpt:
#  token: "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"
#  proxy-host: 127.0.0.1 #需要代理时必填
#  proxy-port: 8080 #需要代理时必填
#  chat-model: gpt-3.5-turbo
#  session-expiration-time: 10

openai:
  #  proxyHost: "127.0.0.1"
  #  proxyPort: 7890
  keys: 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

server:
  port: 8081


youdao:
  appKey: 50be7e8bacf473b5
  appSecret: pxyFC30Yz0Ak1uyu3udaKH2SULpDw57j
  from: auto
  to: zh-CHS


#  tapviaweblong1986@outlook.com----aTypKH10AQ----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----sess-vMLe5KeC9iJOMdavQs86pjd51YlDzkkHR3e8wINE
#  apinlooli1978@outlook.com----9CNgOr4oDY----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----sess-NysTcpVwz4nH8ahqtQlELDLhhMnyK0Lc4uHQrgPZ
